/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// The user who triggered the Pipeline.
type PipelineListResponseTriggerActor struct {
	// The login information for the user on the VCS.
	Login string `json:"login"`
	// URL to the user's avatar on the VCS
	AvatarUrl string `json:"avatar_url"`
}
