/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

type TestsResponseItems struct {
	// The failure message associated with the test.
	Message string `json:"message"`
	// The program that generated the test results
	Source string `json:"source"`
	// The time it took to run the test in seconds
	RunTime float64 `json:"run_time"`
	// The file in which the test is defined.
	File string `json:"file"`
	// Indication of whether the test succeeded.
	Result string `json:"result"`
	// The name of the test.
	Name string `json:"name"`
	// The programmatic location of the test.
	Classname string `json:"classname"`
}
