/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci

// Information about the VCS that hosts the project source code.
type ProjectVcsInfo struct {
	// URL to the repository hosting the project's code
	VcsUrl string `json:"vcs_url"`
	// The VCS provider
	Provider string `json:"provider"`
	DefaultBranch string `json:"default_branch"`
}
