/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package circleci
import (
	"time"
)

type InlineResponse2002Items struct {
	// The name of the job.
	Name string `json:"name"`
	// The start of the aggregation window for job metrics.
	WindowStart time.Time `json:"window_start"`
	// The end of the aggregation window for job metrics.
	WindowEnd time.Time `json:"window_end"`
	Metrics *InlineResponse2002Metrics `json:"metrics"`
}
