/*
 * CircleCI API
 *
 * This describes the resources that make up the CircleCI API v2. API v2 is currently in Preview. Additional documentation for this API can be found in the [API Preview Docs](https://github.com/CircleCI-Public/api-preview-docs/tree/master/docs). Breaking changes to the API will be announced in the [Breaking Changes log](https://github.com/CircleCI-Public/api-preview-docs/blob/master/docs/breaking.md).
 *
 * API version: v2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"time"
)

// Job Details
type JobDetails struct {
	// URL of the job in CircleCI Web UI.
	WebUrl  string             `json:"web_url"`
	Project *JobDetailsProject `json:"project"`
	// Info about parallels runs and their status.
	ParallelRuns []JobDetailsParallelRuns `json:"parallel_runs"`
	// The date and time the job started.
	StartedAt      time.Time                 `json:"started_at"`
	LatestWorkflow *JobDetailsLatestWorkflow `json:"latest_workflow"`
	// The name of the job.
	Name     string              `json:"name"`
	Executor *JobDetailsExecutor `json:"executor"`
	// A number of parallel runs the job has.
	Parallelism int64 `json:"parallelism"`
	// The current status of the job.
	Status *string `json:"status"`
	// The number of the job.
	Number   int64               `json:"number"`
	Pipeline *JobDetailsPipeline `json:"pipeline"`
	// Duration of a job in milliseconds.
	Duration int64 `json:"duration"`
	// The time when the job was created.
	CreatedAt time.Time `json:"created_at"`
	// Messages from CircleCI execution platform.
	Messages []JobDetailsMessages `json:"messages"`
	// List of contexts used by the job.
	Contexts     []JobDetailsContexts    `json:"contexts"`
	Organization *JobDetailsOrganization `json:"organization"`
	// The time when the job was placed in a queue.
	QueuedAt time.Time `json:"queued_at"`
	// The time when the job stopped.
	StoppedAt time.Time `json:"stopped_at,omitempty"`
}
